### ISSUE TITLE
Bug: Using a string containing `.` as a JSON key will cause an error in the JSON View Page

### ISSUE THREAD

**Issue by yandif** [apihero-run/jsonhero-web#98]
## Envirorment:
online : https://jsonhero.io/j/cC6nC3Vgh4s4
## Description
When I use a string containing ’.‘ as a JSON key, I get an error when I switch to the JSON view page.
```JSON
{
  "a.b": "1"
}
```
![image](https://user-images.githubusercontent.com/52165593/191184866-612dce59-cb16-4607-811b-fefe52fae678.png)
![image](https://user-images.githubusercontent.com/52165593/191184969-f4273054-6984-442e-b7c8-ba030e7b1876.png)

And here is the error log.
```
TypeError: Cannot read properties of undefined (reading 'start')
    at https://jsonhero.io/build/routes/j/$id/editor-BQP7CIXM.js:1:1127
    at Gf (https://jsonhero.io/build/_shared/chunk-PZ2Z7HGX.js:9:6560)
    at L.unstable_runWithPriority (https://jsonhero.io/build/_shared/chunk-PZ2Z7HGX.js:1:4026)
    at rn (https://jsonhero.io/build/_shared/chunk-PZ2Z7HGX.js:5:38448)
    at Xe (https://jsonhero.io/build/_shared/chunk-PZ2Z7HGX.js:9:6029)
    at yi (https://jsonhero.io/build/_shared/chunk-PZ2Z7HGX.js:7:10750)
    at https://jsonhero.io/build/_shared/chunk-PZ2Z7HGX.js:5:38670
    at L.unstable_runWithPriority (https://jsonhero.io/build/_shared/chunk-PZ2Z7HGX.js:1:4026)
    at rn (https://jsonhero.io/build/_shared/chunk-PZ2Z7HGX.js:5:38448)
    at Cs (https://jsonhero.io/build/_shared/chunk-PZ2Z7HGX.js:5:38616)
```

**Comment by Kit-p** [comment]
Hi, is it okay for me to work on this issue?

**Comment by ericallam** [comment]
@Kit-p definitely, go for it!
